#!/usr/bin/env bash

# DESCRIPTION
#
# Exécute un ou plusieurs scripts de test contenus dans un répertoire.
#
# USAGE
#
# tester.sh REPERTOIRE? EXERCICE*
#

# déterminer le répertoire contenant les tests : celui spécifié ou .Tests
if [[ -d "$1" ]]; then
    repertoire="$(realpath "$1")"
    shift 
else
    repertoire="$(pwd)/.Tests"
    if [[ ! -d "${repertoire}" ]]; then
        echo "$(basename $0) : répertoire de test non spécifié" 1>&2
        exit 1
    fi
fi

# déterminer les exercices à tester
if [[ -n "$@" ]]; then
    exercices="$@"
elif [[ -f "${repertoire}/bareme.txt" ]]; then
    while read exercice points; do
        exercices="${exercices}${exercice} "
    done < "${repertoire}/bareme.txt"
else 
    exercices="$(find ${repertoire} -name 'test-*' -exec basename {} \; | \
        cut -d - -f 2-)"
fi

# exécuter le test des exercices
for exercice in ${exercices}; do
    exercice="${exercice%.*}" # supprime l'eventuel suffixe (completion automatique)
    test="${repertoire}/test-${exercice}"
    if [[ -d "${test}" ]]; then
        test="${test}/test"
    fi
    if [[ ! -x "${test}" ]]; then
        echo "$(basename $0) : testeur \"${exercice}\" absent" 1>&2
        continue
    fi
    ${test}
done
