#!/usr/bin/env bash

# DESCRIPTION
#
# Exécute un ou plusieurs scripts de test contenus dans un répertoire.
#
# USAGE
#
# tester.sh [REPERTOIRE] [EXERCICE]...
#

# déterminer le répertoire contenant les tests :
# celui spécifié, à défaut .Tests
if [[ -d "$1" ]]; then
    repertoire="$(realpath "$1")"
    shift 
else
    repertoire="$(pwd)/.Tests"
    if [[ ! -d "${repertoire}" ]]; then
        echo "$(basename $0) : pas de répertoire de test" 1>&2
        exit 1
    fi
fi

# déterminer les exercices à tester :
# ceux spécifiés, à défaut ceux du barème, à défaut ceux du réperoire de test
if [[ -n "$@" ]]; then
    exercices="$@"
elif [[ -f "${repertoire}/bareme.txt" ]]; then
    while read exercice points; do
        exercices="${exercices}${exercice} "
    done < "${repertoire}/bareme.txt"
else 
    exercices="$(find ${repertoire} -name 'test-*' -exec basename {} \; | \
        cut -d - -f 2-)"
fi
if [[ -z "${exercices}" ]]; then
    echo "$(basename $0) : pas d'exercice à tester" 1>&2
    exit 1
fi

# exécuter le test des exercices :
# test-exercice si fichier, test-exercice/test si répertoire, test à défaut 
for exercice in ${exercices}; do
    exercice="${exercice%.*}" # supprime l'eventuel suffixe (completion automatique)
    test="${repertoire}/test-${exercice}"
    if [[ ! -e "${test}" ]]; then
        test="${repertoire}/test"
        args="${exercice}"
    fi
    if [[ -d "${test}" ]]; then
        test="${test}/test"
    fi
    if [[ ! -x "${test}" ]]; then
        echo "$(basename $0) : testeur \"${exercice}\" absent" 1>&2
        continue
    fi
    ${test} ${args}
done
