#!/usr/bin/env python3

from CAButilitaires import *

# prologue
CABinitier(f"{CABexercice()}.py")

# tests
parametres = "ordre"
jeux = [ \
    (2, [[1], [1, 1], [1, 2, 1]]), \
    (3, [[1], [1, 1], [1, 2, 1], [1, 3, 3, 1]]) \
]
fonction = CABimporter(CABexercice(), CABexercice())

for jeu in jeux:
    # arguments et attendu
    ordre = jeu[0]
    attendu = jeu[1]
    # presentation arguments
    entrees = f"{jeu[0]}"
    # appel fonction
    obtenu = fonction(ordre)
    # vérification
    CABverifier(100 / len(jeux), f"{parametres} = {entrees} => {attendu} ?", str(obtenu == attendu), f", obtenu : {obtenu}")  

# epilogue
CABterminer()

