#!/usr/bin/env python3

from CAButilitaires import *

# utilitaire
def sontEgaux(obtenu: list[list], attendu: list[list]) -> bool:
    if len(obtenu) != len(attendu):
        return False
    for liste in attendu:
        if not liste in obtenu:
            return False
    return True

# prologue
CABinitier(f"{CABexercice()}.py")

# tests
parametres = "ensemble, p"
jeux = [ \
    ({1, 2, 3}, 1, [[1], [2], [3]]), \
    ({1, 2, 3}, 2, [[1, 2], [1, 3], [2, 1], [2, 3], [3, 1], [3, 2]]), \
    ({1, 2, 3}, 3, [[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]) \
]
fonction = CABimporter(CABexercice(), CABexercice())

for jeu in jeux:
    # argumens et attendu
    ensemble = set(jeu[0])
    p = jeu[1]
    attendu = jeu[2]
    # presentation arguments
    entrees = f"{jeu[0]}, {jeu[1]}"
    # appel fonction
    obtenu = fonction(ensemble, p)
    # vérification
    CABverifier(100 / len(jeux), f"{parametres} = {entrees} => {attendu} ?", str(sontEgaux(obtenu, attendu)), f", obtenu : {obtenu}")  

# epilogue
CABterminer()

