#!/usr/bin/env bash

source .Tests/CAButilitaires.sh

# prologue
CABinitier ${EXERCICE}.sh

# tests
# - cas normal
CABexecuter '' ./${EXERCICE}.sh 3 0 -3
CABverifier 50 './min_max.sh 3 0 -3 => 1> == -3 3 ?' '[[ $(cat .out) == "-3 3" ]]' ", obtenu : $(cat .out)"
CABverifier -10 './min_max.sh 3 0 -3 => 2> == "" ?' '[[ -z $(cat .err) ]]' ", obtenu : $(cat .err)"
CABverifier -10 './min_max.sh 3 0 -3 => $? == 0 ?' '(( $(cat .stat) == 0 ))' ", obtenu : $(cat .stat)"

# - cas limite une valeur
CABexecuter '' ./${EXERCICE}.sh 1
CABverifier 20 './min_max.sh 1 => 1> == 1 1 ?' '[[ $(cat .out) == "1 1" ]]' ", obtenu : $(cat .out)"

# - cas d'erreur pas d'argument
CABexecuter '' ./${EXERCICE}.sh
CABverifier 10 './min_max.sh => 1> == "" ?' '[[ -z $(cat .out) ]]' ", obtenu : $(cat .out)"
CABverifier 10 './min_max.sh => 2> == "...min_max.sh..." ?' 'grep -qi min_max.sh .err' ", obtenu : $(cat .err)"
CABverifier 10 './min_max.sh => $? != 0 ?' '(( $(cat .stat) != 0 ))' ", obtenu : $(cat .stat)"

# épilogue
CABterminer

