#!/usr/bin/env bash

source .Tests/CAButilitaires.sh 2> /dev/null || source CAButilitaires.sh

# prologue
CABinitier $(CABexercice).py

# tests
jeux=" \
=vide \
A=A~A \
bonjour=b~u \
Hi!=!~i \
"

CABjouer "python $(CABexercice).py" "chaine" ${jeux}

# épilogue
CABterminer
