#!/usr/bin/env bash

source .Tests/CAButilitaires.sh 2> /dev/null || source CAButilitaires.sh

# prologue
CABinitier $(CABexercice).py

# tests
jeux=" \
=True \
bob=True \
ELLE=True \
Bob=False \
"

CABjouer "python $(CABexercice).py" "chaine" ${jeux}

# épilogue
CABterminer
