#!/usr/bin/env bash

source .Tests/CAButilitaires.sh 2> /dev/null || source CAButilitaires.sh

# prologue
CABinitier $(CABexercice).py

# tests
jeux=" \
=False \
bonjour=True \
bOnjour=False \
aa=True \
"

CABjouer "python $(CABexercice).py" "chaine" ${jeux}

# épilogue
CABterminer
